x-sandbox-base: &sandbox-base
  image: rtl-wizard-sandbox:latest
  command: "tail -f /dev/null"
  init: true
  stop_grace_period: 1s

services:
  solver:
    <<: *sandbox-base
    x-default: true
    build:
      context: ../server
      dockerfile: ../sandbox/Dockerfile
  scorer:
    <<: *sandbox-base
    x-local: true
