#!/usr/bin/env bash
# secworks/modexp self-checking testbench (Strombergson). The patch enables
# five fast vectors in tb_modexp -- tc1-3 plus the autogenerated BASIC 33-bit
# and 128-bit cases -- and disables the slow 1024-bit rob_enc case and the
# upstream work-in-progress e65537 cases. Pass = the bench's own self-check
# line "All NN test cases completed successfully" (error count zero).
set -eo pipefail
cd toolruns
make modexp.sim
./modexp.sim | tee modexp.log
grep -q 'test cases completed successfully' modexp.log
